In [ ]:
import torch
from torch.autograd.function import Function
import torch.nn.functional as F
import numpy as np
import math

ModuleNotFoundError: No module named 'conv'

# 张量相关函数


## torch.tensor


In [3]:
l = [[1., -1.], [1., -1.]]
t_from_list = torch.tensor(l)
arr = np.array([[1, 2, 3], [4, 5, 6]])
t_from_array = torch.tensor(arr)
print(t_from_list, t_from_list.dtype)
print(t_from_array, t_from_array.dtype)

tensor([[ 1., -1.],
        [ 1., -1.]]) torch.float32
tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32) torch.int32


## torch.from_numpy


In [4]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
t_from_numpy = torch.from_numpy(arr)
print("numpy array: ", arr)
print("tensor : ", t_from_numpy)
print("\n修改arr")
arr[0, 0] = 0
print("numpy array: ", arr)
print("tensor : ", t_from_numpy)
print("\n修改tensor")
t_from_numpy[0, 0] = -1
print("numpy array: ", arr)
print("tensor : ", t_from_numpy)

numpy array:  [[1 2 3]
 [4 5 6]]
tensor :  tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)

修改arr
numpy array:  [[0 2 3]
 [4 5 6]]
tensor :  tensor([[0, 2, 3],
        [4, 5, 6]], dtype=torch.int32)

修改tensor
numpy array:  [[-1  2  3]
 [ 4  5  6]]
tensor :  tensor([[-1,  2,  3],
        [ 4,  5,  6]], dtype=torch.int32)


## torch.zeros


In [5]:
o_t = torch.tensor([1])
print(o_t, '\n')
t = torch.zeros((3, 3), out=o_t)
print(t, '\n', o_t)
print(id(t), id(o_t))

tensor([1]) 

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]) 
 tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
1999468913648 1999468913648


## torch.zeros_like


In [6]:
t1 = torch.tensor([[1., -1.], [1., -1.]])
t2 = torch.zeros_like(t1)
print(t2)

tensor([[0., 0.],
        [0., 0.]])


## torch.ones/torch.ones_like/torch.full/torch.full_like


In [7]:
print(torch.full((2, 3), 3.141592))

tensor([[3.1416, 3.1416, 3.1416],
        [3.1416, 3.1416, 3.1416]])


## torch.arange


In [8]:
# 创建等差的1维张量，长度为 (end-start)/step，需要注意数值区间为[start, end)。
# 主要参数：
# start (Number) – 数列起始值，默认值为0。the starting value for the set of points. Default: 0.
# end (Number) – 数列的结束值。
# step (Number) – 数列的等差值，默认值为1。
# out (Tensor, optional) – 输出的tensor，即该函数返回的tensor可以通过out进行赋值。
print(torch.arange(1, 2.51, 0.5))

tensor([1.0000, 1.5000, 2.0000, 2.5000])


## torch.linspace


In [9]:
# 创建均分的1维张量，长度为steps，区间为[start, end]。
# 主要参数：
# start (float) – 数列起始值
# end (float) – 数列结束值。
# steps (int) – 数列长度。
print(torch.linspace(3, 10, steps=5))
print(torch.linspace(1, 5, steps=3))

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])
tensor([1., 3., 5.])


## torch.logspace


In [10]:
# 创建对数均分的1维张量，长度为steps, 底为base。
# 主要参数：
# start (float) – 确定数列起始值为base^start
# end (float) – 确定数列结束值为base^end
# steps (int) – 数列长度。
# base (float) - 对数函数的底，默认值为10，此参数是在pytorch 1.0.1版本之后加入的。
print(np.log10(2.1135))
print(np.log10(3.5481))
print(np.log10(5.9566))
print(torch.logspace(start=0.1, end=1.0, steps=5))
print(torch.logspace(start=2, end=2, steps=1, base=2))

0.3250022521650377
0.5499958515306512
0.7749984371602154
tensor([ 1.2589,  2.1135,  3.5481,  5.9566, 10.0000])
tensor([4.])


## torch.eye


In [11]:
# 创建单位对角矩阵。
# 主要参数：
# n (int) - 矩阵的行数
# m (int, optional) - 矩阵的列数，默认值为n，即默认创建一个方阵
print(np.eye(3))
print(np.eye(3, 4))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


## torch.empty


In [12]:
# ：依size创建“空”张量，这里的“空”指的是不会进行初始化赋值操作。
# 主要参数：
# size (int...) - 张量维度
# pin_memory (bool, optional) - pinned memory 又称page locked memory，即锁页内存，该参数用来指示是否将tensor存
# 于锁页内存，通常为False，若内存足够大，建议设置为True，这样在转到GPU时会快一些。
torch.empty(2, 3)

tensor([[1.8159e+16, 1.1210e-42, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])

## torch.empty_like(


In [13]:
# torch.empty_like之于torch.empty等同于torch.zeros_like之于torch.zeros，因此不再赘述。
torch.empty_like(t1)

tensor([[1.8029e+16, 1.1210e-42],
        [5.0000e+00, 0.0000e+00]])

## torch.empty_strided


In [14]:
# 依size创建“空”张量，这里的“空”指的是不会进行初始化赋值操作。
# 主要参数：
# stride (tuple of python:ints) - 张量存储在内存中的步长，是设置在内存中的存储方式。
# size (int...) - 张量维度
# pin_memory (bool, optional) - 是否存于锁页内存

# 这里 stride=(4,1)，表示：
# 在第一维（行），每跨 1 步，需要跳 4 个元素。
# 在第二维（列），每跨 1 步，需要跳 1 个元素。
# 这等价于 torch.empty((3,4))，使用的是默认的 行优先（Row-major） 存储方式。
# 创建一个 (3, 4) 形状的张量，步幅 (4, 1)，即默认的连续内存布局
tensor = torch.empty_strided((3, 4), (4, 1))
print(tensor)

# 这里 stride=(1, 3)，表示：
# 在第一维（行），每跨 1 步，只跳 1 个元素（行数据变得不连续）。
# 在第二维（列），每跨 1 步，需要跳 3 个元素。
# 这会导致列变得不连续，因为通常 PyTorch 张量是行优先存储的，而这里的 stride 让数据以列优先的方式存储。
# # 创建一个 (3, 4) 形状的张量，步幅 (1, 3)
tensor = torch.empty_strided((3, 4), (1, 3))
print(tensor)

# 这里 stride=(1,2)，表示：
# 在 第一维（行），每前进 1 步，跳 1 个元素。
# 在 第二维（列），每前进 1 步，跳 2 个元素（表示列是主维度）。
# 这个张量的 内存布局与其转置匹配，可以更高效地执行 tensor.t()。
# 创建一个 (2, 3) 形状的张量，并让它的步幅与转置 (3, 2) 形状匹配
tensor = torch.empty_strided((2, 3), (1, 2))  # 行步幅=1，列步幅=2
print(tensor)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


## torch.normal


In [15]:
# 为每一个元素以给定的mean和std用高斯分布生成随机数
# 主要参数：
# mean (Tensor or Float) - 高斯分布的均值，
# std (Tensor or Float) - 高斯分布的标准差
# 特别注意事项：
# mean和std的取值分别有2种，共4种组合，不同组合产生的效果也不同，需要注意
# mean为张量，std为张量，torch.normal(mean, std, out=None)，每个元素从不同的高斯分布采样，分布的均值和标准差
# 由mean和std对应位置元素的值确定；
# mean为张量，std为标量，torch.normal(mean, std=1.0, out=None)，每个元素采用相同的标准差，不同的均值；
# mean为标量，std为张量，torch.normal(mean=0.0, std, out=None)， 每个元素采用相同均值，不同标准差；
# mean为标量，std为标量，torch.normal(mean, std, size, *, out=None) ，从一个高斯分布中生成大小为size的张量
mean = torch.arange(1, 11.)
std = torch.arange(1, 0, -0.1)
normal = torch.normal(mean=mean, std=std)
# normal第一个元素是从均值为1，标准差为1的高斯分布中采样得到的
# 第二个元素是从均值为2，标准差为0.9的高斯分布中采样得到的
print("mean: {}, \nstd: {}, \nnormal: {}".format(mean, std, normal))

mean: tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), 
std: tensor([1.0000, 0.9000, 0.8000, 0.7000, 0.6000, 0.5000, 0.4000, 0.3000, 0.2000,
        0.1000]), 
normal: tensor([ 1.7729,  2.2683,  1.8957,  4.1742,  4.7767,  6.4824,  6.7675,  8.6944,
         8.7786, 10.0303])


## torch.rand


In [16]:
# 在区间[0, 1)上，生成均匀分布。
torch.rand(2, 3)

tensor([[0.8808, 0.3411, 0.3451],
        [0.9658, 0.4336, 0.2045]])

## torch.randint


In [17]:
# 在区间[low, high)上，生成整数的均匀分布。
torch.randint(3, 5, (2, 3))

tensor([[3, 3, 3],
        [3, 4, 3]])

## torch.randint_like


In [ ]:
# torch.randint_like之于torch.randint等同于torch.zeros_like之于torch.zeros，
torch.randint_like(t1, 3, 5)

tensor([[3., 4.],
        [3., 4.]])

## torch.randn


In [20]:
# 生成形状为size的标准正态分布张量。
torch.randn(2, 3)

tensor([[ 0.8908,  0.6130, -0.9899],
        [-0.5479,  1.1192, -0.3060]])

# torch.randn_like


In [21]:
torch.randn_like(t1)

tensor([[ 0.8675, -0.4630],
        [ 0.3928,  0.7077]])

## torch.randperm


In [ ]:
# 生成从0到n-1的随机排列。perm == permutation
torch.randperm(5)

tensor([1, 0, 4, 2, 3])

## torch.bernoulli


In [ ]:
# 以input的值为概率，生成伯努力分布（0-1分布，两点分布）。
# # 生成一个 3×3 的张量，每个元素在 [0,1) 之间均匀分布
p = torch.empty(3, 3).uniform_(0, 1)
# 以 p 的值作为成功概率，生成伯努利分布（0 或 1）
b = torch.bernoulli(p)
print("probability: \n{}, \nbernoulli_tensor:\n{}".format(p, b))

probability: 
tensor([[0.8292, 0.3662, 0.0520],
        [0.2720, 0.6393, 0.6570],
        [0.5829, 0.5551, 0.7389]]), 
bernoulli_tensor:
tensor([[1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.]])


## torch.gather


In [25]:
# 定义一个 1 维张量
input = torch.tensor([10, 20, 30, 40, 50])
# 定义索引张量
index = torch.tensor([3, 0, 4])
# 在 dim=0 维度上收集数据
output = torch.gather(input, dim=0, index=index)
print(output)  # 输出: tensor([40, 10, 50])

tensor([40, 10, 50])


In [ ]:
input = torch.tensor([[10, 20, 30],
                      [40, 50, 60],
                      [70, 80, 90]])
index = torch.tensor([[2, 1, 0],
                      [0, 2, 1],
                      [1, 0, 2]])
output = torch.gather(input, dim=0, index=index)
print(output)

tensor([[70, 50, 30],
        [10, 80, 60],
        [40, 20, 90]])


In [ ]:
input = torch.tensor([[10, 20, 30],
                      [40, 50, 60],
                      [70, 80, 90]])
index = torch.tensor([[2, 0, 1],
                      [1, 2, 0],
                      [0, 1, 2]])
output = torch.gather(input, dim=1, index=index)
print(output)

tensor([[30, 10, 20],
        [50, 60, 40],
        [70, 80, 90]])


In [28]:
# 假设是一个 3 样本 × 4 类的 logits（未归一化概率）
logits = torch.tensor([[0.1, 2.5, 0.3, 1.8],
                       [1.2, 0.4, 3.1, 2.0],
                       [2.1, 3.5, 0.5, 0.7]])

# 获取每个样本 Top-2 的索引和分数
top2_scores, top2_indices = torch.topk(logits, k=2, dim=1)

print("Top-2 scores:\n", top2_scores)
print("Top-2 indices:\n", top2_indices)

Top-2 scores:
 tensor([[2.5000, 1.8000],
        [3.1000, 2.0000],
        [3.5000, 2.1000]])
Top-2 indices:
 tensor([[1, 3],
        [2, 3],
        [1, 0]])


In [ ]:
# 假设 batch_size=2, seq_len=5, vocab_size=4
logits = torch.tensor([[[0.1, 0.3, 2.1, 1.7],
                        [1.2, 2.5, 0.4, 1.9],
                        [1.3, 1.1, 2.8, 0.7],
                        [2.2, 0.6, 1.4, 3.0],
                        [0.5, 2.3, 1.7, 0.9]],
                       [[1.1, 2.3, 0.8, 1.4],
                        [0.6, 1.7, 2.1, 1.2],
                        [1.0, 0.5, 2.6, 1.3],
                        [0.4, 3.2, 1.5, 2.0],
                        [1.8, 1.1, 0.9, 2.7]]])
# 目标索引（假设真实的词索引）
target_indices = torch.tensor([[2, 1, 2, 3, 1],
                               [1, 2, 2, 1, 3]])
# 获取 target_indices 对应的 logits
target_logits = torch.gather(
    logits, dim=2, index=target_indices.unsqueeze(-1)).squeeze(-1)
print(target_logits)

tensor([[2.1000, 2.5000, 2.8000, 3.0000, 2.3000],
        [2.3000, 2.1000, 2.6000, 3.2000, 2.7000]])


## scater


In [ ]:
# scatter_(dim, index, src, reduce=None) → Tensor。将src中数据根据index中的索引按照dim的方向
# 填进input中。这是一个十分难理解的函数，其中index是告诉你哪些位置需要变，src是告诉你要变
# 的值是什么。
input_tensor = torch.zeros(3, 3)
index = torch.tensor([[0, 1, 2],
                      [1, 2, 0],
                      [2, 0, 1]])
src = torch.tensor([[10, 20, 30],
                    [40, 50, 60],
                    [70, 80, 90]])
src = src.to(input_tensor.dtype)  # 转换 src 数据类型
# 在 dim=0（行方向）上 scatter
result = input_tensor.scatter(dim=0, index=index, src=src)
print(result)

tensor([[10., 80., 60.],
        [40., 20., 90.],
        [70., 50., 30.]])


## 计算图


In [ ]:
w = torch.tensor([1.], requires_grad=True)
x = torch.tensor([2.], requires_grad=True)
a = torch.add(w, x)
b = torch.add(w, 1)  # retain_grad()
y = torch.mul(a, b)
y.backward()
print(w.grad)
# 查看叶子结点
print("is_leaf:\n", w.is_leaf, x.is_leaf, a.is_leaf, b.is_leaf, y.is_leaf)
# 查看梯度
print("gradient:\n", w.grad, x.grad, a.grad, b.grad, y.grad)
# 查看 grad_fn
print("grad_fn:\n", w.grad_fn, x.grad_fn, a.grad_fn, b.grad_fn, y.grad_fn)

tensor([5.])
is_leaf:
 True True False False False
gradient:
 tensor([5.]) tensor([2.]) None None None
grad_fn:
 None None <AddBackward0 object at 0x000001D189B75A20> <AddBackward0 object at 0x000001D189B74A00> <MulBackward0 object at 0x000001D189B75390>


C:\Users\Hankuke.D\AppData\Local\Temp\ipykernel_22612\3464209613.py:11: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at C:\cb\pytorch_1000000000000\work\build\aten\src\ATen/core/TensorBody.h:494.)
  print("gradient:\n", w.grad, x.grad, a.grad, b.grad, y.grad)


## backward


In [35]:
w = torch.tensor([1.], requires_grad=True)
x = torch.tensor([2.], requires_grad=True)
a = torch.add(w, x)
b = torch.add(w, 1)
y = torch.mul(a, b)
y.backward(retain_graph=True)
print(w.grad)
y.backward()
print(w.grad)

tensor([5.])
tensor([10.])


In [ ]:
# 报错
w = torch.tensor([1.], requires_grad=True)
x = torch.tensor([2.], requires_grad=True)
a = torch.add(w, x)
b = torch.add(w, 1)
y = torch.mul(a, b)
y.backward()
print(w.grad)
y.backward()
print(w.grad)

tensor([5.])


RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.

: 

## grad_tensors


In [ ]:
w = torch.tensor([1.], requires_grad=True)
x = torch.tensor([2.], requires_grad=True)
a = torch.add(w, x)
b = torch.add(w, 1)
y0 = torch.mul(a, b)  # y0 = (x+w) * (w+1) dy0/dw = 2w + x + 1
y1 = torch.add(a, b)  # y1 = (x+w) + (w+1) dy1/dw = 2
loss = torch.cat([y0, y1], dim=0)  # [y0, y1]
# rad_tensors=[1., 2.] 作用是加权求梯度，决定 y0 和 y1 在最终梯度中的贡献。
# 若 grad_tensors=[1., 1.]，则所有 loss 元素等权重贡献。
# 你的 grad_tensors=[1., 2.] 代表 y1 的贡献是 y0 的两倍。
grad_tensors = torch.tensor([1., 2.])
# Tensor.backward中的 gradient 传入 torch.autograd.backward()中的grad_tensors
loss.backward(gradient=grad_tensors)
# w = 1* (dy0/dw) + 2*(dy1/dw)
# w = 1* (2w + x + 1) + 2*(w)
# w = 1* (5) + 2*(2)
# w = 9
print(w.grad)

tensor([9.])


## torch.autograd.grad


In [ ]:
# 计算outputs对inputs的导数
# 主要参数：
# outputs (sequence of Tensor) – 用于求导的张量，如loss
# inputs (sequence of Tensor) – 所要计算导数的张量
# grad_outputs (sequence of Tensor) – 雅克比向量积中使用。
# retain_graph (bool, optional) – 是否需要保留计算图。pytorch的机制是在方向传播结束时，计算图释放以节省内
# 存。大家可以尝试连续使用loss.backward()，就会报错。如果需要多次求导，则在执行backward()时，
# retain_graph=True。
# create_graph (bool, optional) – 是否创建计算图，用于高阶求导。
# allow_unused (bool, optional) – 是否需要指示，计算梯度时未使用的张量是错误的
x = torch.tensor([3.], requires_grad=True)
y = torch.pow(x, 2)  # y = x**2
# 一阶导数
# grad_1 = dy/dx = 2x = 2 * 3 = 6
grad_1 = torch.autograd.grad(y, x, create_graph=True)
print(grad_1)
# 二阶导数
# grad_2 = d(dy/dx)/dx = d(2x)/dx = 2
grad_2 = torch.autograd.grad(grad_1[0], x)
print(grad_2)

(tensor([6.], grad_fn=<MulBackward0>),)
(tensor([2.]),)


## torch.autograd.Function


In [ ]:
# 有的时候，想要实现自己的一些操作（op），如特殊的数学函数、pytorch的module中没有的网络层，那就需要自己写
# 一个Function，在Function中定义好forward的计算公式、backward的计算公式，然后将这些op组合到模型中，模型就可
# 以用autograd完成梯度求取。
class Exp(Function):
    @staticmethod
    def forward(ctx, i):
        # ============== step1: 函数功能实现 ==============
        result = i.exp()
        # ============== step1: 函数功能实现 ==============
        # ============== step2: 结果保存，用于反向传播 ==============
        ctx.save_for_backward(result)
        # ============== step2: 结果保存，用于反向传播 ==============
        return result

    @staticmethod
    def backward(ctx, grad_output):
        # ============== step1: 取出结果，用于反向传播 ==============
        result, = ctx.saved_tensors
        # ============== step1: 取出结果，用于反向传播 ==============
        # ============== step2: 反向传播公式实现 ==============
        grad_results = grad_output * result
        # ============== step2: 反向传播公式实现 ==============
        return grad_results


x = torch.tensor([1.], requires_grad=True)
y = Exp.apply(x)  # 需要使用apply方法调用自定义autograd function
print(y)  # y = e^x = e^1 = 2.7183
y.backward()
print(x.grad)  # 反传梯度, x.grad = dy/dx = e^x = e^1 = 2.7183

tensor([2.7183], grad_fn=<ExpBackward>)
tensor([2.7183])


## Gradcoeff

反向传梯度时乘以一个自定义系数


In [10]:
class GradCoeff(Function):
    @staticmethod
    def forward(ctx, x, coeff):
        # ============== step1: 函数功能实现 ==============
        ctx.coeff = coeff  # 将coeff存为ctx的成员变量
        x.view_as(x)  # 这个语句没有实际作用，可以删除
        # ============== step1: 函数功能实现 ==============
        # x=x ** 2
        return x  # 直接返回 x

    @staticmethod
    def backward(ctx, grad_output):
        # backward的输出个数应与 forward 的输入个数相同
        # 此处 coeff 不需要梯度，因此返回 None
        return ctx.coeff * grad_output, None  # 仅 x 需要梯度，coeff 不需要梯度


# 尝试使用
x = torch.tensor([2.], requires_grad=True)
ret = GradCoeff.apply(x, -0.1)  # 前向传播不会影响 x，仅存储 coeff = -0.1
ret = ret ** 2  # ret = x^2
print(ret)  # 观察 ret.grad_fn
ret.backward()
print(x.grad)  # 观察 x 的梯度
# tensor([4.])：这是 ret = x^2 的前向计算结果。
# tensor([-0.4])：是 x 的梯度，说明 coeff 确实在反向传播时起作用。

tensor([4.], grad_fn=<PowBackward0>)
tensor([-0.4000])


## 勒让德多项式


In [ ]:
class LegendrePolynomial3(Function):
    @staticmethod
    def forward(ctx, x):
        """
        In the forward pass we receive a Tensor containing the input and return
        a Tensor containing the output. ctx is a context object that can be used
        to stash information for backward computation. You can cache arbitrary
        objects for use in the backward pass using the ctx.save_for_backward method.
        """
        y = 0.5 * (5 * x ** 3 - 3 * x)
        ctx.save_for_backward(x)
        return y

    @staticmethod
    def backward(ctx, grad_output):
        """
        In the backward pass we receive a Tensor containing the gradient of the loss
        with respect to the output, and we need to compute the gradient of the loss
        with respect to the input.
        """
        ret, = ctx.saved_tensors
        return grad_output * 1.5 * (5 * ret ** 2 - 1)


a, b, c, d = 1, 2, 1, 2
x = 1
P3 = LegendrePolynomial3.apply
y_pred = a + b * P3(c + d * x)
print(y_pred)

127.0


## 手动实现 2D 卷积


In [ ]:
def convolution_backward(grad_out, X, weight):
    """ 反向传播函数，返回与 forward 输入参数数目一致的梯度 """
    grad_X = F.conv_transpose2d(grad_out, weight)  # 计算 X 的梯度
    grad_weight = F.conv2d(X.transpose(0, 1), grad_out.transpose(
        0, 1)).transpose(0, 1)  # 计算 weight 的梯度
    return grad_X, grad_weight


class MyConv2D(torch.autograd.Function):
    @staticmethod
    def forward(ctx, X, weight):
        ctx.save_for_backward(X, weight)
        return F.conv2d(X, weight)

    @staticmethod
    def backward(ctx, grad_out):
        X, weight = ctx.saved_tensors
        return convolution_backward(grad_out, X, weight)


# 测试
weight = torch.rand(5, 3, 3, 3, requires_grad=True, dtype=torch.double)
X = torch.rand(10, 3, 7, 7, requires_grad=True, dtype=torch.double)
# 检查自定义的 Autograd Function 是否正确
# torch.autograd.gradcheck(MyConv2D.apply, (X, weight)) 在调用正向传播 y = MyConv2D.apply(X, weight) 之前的原因 是因为 gradcheck 本质上会自己执行 forward 和 backward，并进行数值梯度验证。
torch.autograd.gradcheck(MyConv2D.apply, (X, weight))
y = MyConv2D.apply(X, weight)
label = torch.randn_like(y)
loss = F.mse_loss(y, label)
print("Before backward:", weight.grad)
loss.backward()
print("After backward:", weight.grad)

Before backward: None
After backward: tensor([[[[1.2584, 1.3009, 1.2439],
          [1.2616, 1.2758, 1.1893],
          [1.2007, 1.2413, 1.1897]],

         [[1.1759, 1.2055, 1.2032],
          [1.1251, 1.1885, 1.2216],
          [1.1865, 1.2187, 1.1936]],

         [[1.1953, 1.2126, 1.1893],
          [1.2210, 1.2172, 1.2267],
          [1.3208, 1.2731, 1.2899]]],


        [[[1.4673, 1.5456, 1.4312],
          [1.4455, 1.4835, 1.4049],
          [1.3941, 1.4593, 1.3443]],

         [[1.3166, 1.4030, 1.4102],
          [1.3215, 1.3903, 1.3953],
          [1.3581, 1.4129, 1.4145]],

         [[1.3849, 1.4062, 1.4063],
          [1.4378, 1.4148, 1.4395],
          [1.4994, 1.4943, 1.4856]]],


        [[[1.5341, 1.6044, 1.5186],
          [1.5154, 1.5646, 1.4659],
          [1.4746, 1.5180, 1.4588]],

         [[1.3969, 1.4951, 1.4863],
          [1.3774, 1.4612, 1.4730],
          [1.4444, 1.4884, 1.5019]],

         [[1.4678, 1.4716, 1.4589],
          [1.5093, 1.5251, 1.5028],
      

## autograd


In [ ]:
# 知识点一：梯度不会自动清零
w = torch.tensor([1.], requires_grad=True)
x = torch.tensor([2.], requires_grad=True)
for i in range(4):
    a = torch.add(w, x)
    b = torch.add(w, 1)
    y = torch.mul(a, b)
    y.backward()
    print(w.grad)  # 梯度不会自动清零，数据会累加， 通常需要采用 optimizer.zero_grad() 完成对参数的梯度清零
# w.grad.zero_()

tensor([5.])
tensor([10.])
tensor([15.])
tensor([20.])


In [21]:
# 知识点二：依赖于叶子结点的结点，requires_grad默认为True
w = torch.tensor([1.], requires_grad=True)
x = torch.tensor([2.], requires_grad=True)
a = torch.add(w, x)
b = torch.add(w, 1)
y = torch.mul(a, b)
print(a.requires_grad, b.requires_grad, y.requires_grad)
print(a.is_leaf, b.is_leaf, y.is_leaf)

True True True
False False False


In [22]:
# 知识点三：叶子张量不可以执行in-place操作
a = torch.ones((1, ))
print(id(a), a)
a = a + torch.ones((1, ))
print(id(a), a)
a += torch.ones((1, ))
print(id(a), a)

1943963332688 tensor([1.])
1943963333360 tensor([2.])
1943963333360 tensor([3.])


In [23]:
w = torch.tensor([1.], requires_grad=True)
x = torch.tensor([2.], requires_grad=True)
a = torch.add(w, x)
b = torch.add(w, 1)
y = torch.mul(a, b)
w.add_(1)
y.backward()

RuntimeError: a leaf Variable that requires grad is being used in an in-place operation.

In [24]:
# 知识点四：detach 的作用
# detach的作用是：从计算图中剥离出“数据”，并以一个新张量的形式返回，并且新张量与旧张量共享数据，简单的可理
# 解为做了一个别名。
w = torch.tensor([1.], requires_grad=True)
x = torch.tensor([2.], requires_grad=True)
a = torch.add(w, x)
b = torch.add(w, 1)
y = torch.mul(a, b)
y.backward()
w_detach = w.detach()
w_detach.data[0] = 999
print(w)

tensor([999.], requires_grad=True)


In [ ]:
# 知识点五：with torch.no_grad()的作用
# autograd自动构建计算图过程中会保存一系列中间变量，以便于backward的计算，这就必然需要花费额外的内存和时
# 间。
# 而并不是所有情况下都需要backward，例如推理的时候，因此可以采用上下文管理器——torch.no_grad()来管理上下
# 文，让pytorch不记录相应的变量，以加快速度和节省空间。