In [2]:
import torch

## torch.Generator


In [ ]:
# torch.Generator() 主要用于控制随机数生成的状态，可以保证 可复现性
g = torch.Generator().manual_seed(42)  # 设置随机种子
perm1 = torch.randperm(10, generator=g)
perm2 = torch.randperm(10, generator=g)
# torch.randint()：生成一个 包含 32 个随机整数 的张量。
# high=n：指定生成的随机整数范围是 [0, n)，即生成的整数在 0 和 n-1 之间。
# size=(32,)：指定生成 32 个整数。
# dtype=torch.int64：指定生成的整数类型为 64 位整数。
# generator=generator：使用指定的随机数生成器 generator，以确保生成的随机数具有确定性或可复现性。
# .tolist()：将张量转换为 Python 列表，因为 yield 语句通常返回一个列表。
r1 = torch.randint(high=5, size=(11,), dtype=torch.int64,
                   generator=g).tolist()
print(perm1)  # 每次运行都会得到相同的结果
print(perm2)
print(r1)

tensor([2, 6, 1, 8, 4, 5, 0, 9, 3, 7])
tensor([3, 5, 8, 9, 4, 6, 1, 0, 7, 2])
[2, 1, 4, 1, 3, 1, 4, 3, 1, 4, 2]


## torch.randperm


In [12]:
# 生成随机排列
perm = torch.randperm(10)
print(perm)

tensor([3, 1, 5, 6, 7, 0, 4, 2, 8, 9])
