In [1]:
import torch
import numpy as np

# 张量相关函数


## torch.tensor


In [ ]:
l = [[1., -1.], [1., -1.]]
t_from_list = torch.tensor(l)
arr = np.array([[1, 2, 3], [4, 5, 6]])
t_from_array = torch.tensor(arr)
print(t_from_list, t_from_list.dtype)
print(t_from_array, t_from_array.dtype)

tensor([[ 1., -1.],
        [ 1., -1.]]) torch.float32
tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32) torch.int32


## torch.from_numpy


In [3]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
t_from_numpy = torch.from_numpy(arr)
print("numpy array: ", arr)
print("tensor : ", t_from_numpy)
print("\n修改arr")
arr[0, 0] = 0
print("numpy array: ", arr)
print("tensor : ", t_from_numpy)
print("\n修改tensor")
t_from_numpy[0, 0] = -1
print("numpy array: ", arr)
print("tensor : ", t_from_numpy)

numpy array:  [[1 2 3]
 [4 5 6]]
tensor :  tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)

修改arr
numpy array:  [[0 2 3]
 [4 5 6]]
tensor :  tensor([[0, 2, 3],
        [4, 5, 6]], dtype=torch.int32)

修改tensor
numpy array:  [[-1  2  3]
 [ 4  5  6]]
tensor :  tensor([[-1,  2,  3],
        [ 4,  5,  6]], dtype=torch.int32)


## torch.zeros


In [4]:
o_t = torch.tensor([1])
print(o_t, '\n')
t = torch.zeros((3, 3), out=o_t)
print(t, '\n', o_t)
print(id(t), id(o_t))

tensor([1]) 

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]) 
 tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
1950163739440 1950163739440


## torch.zeros_like


In [5]:
t1 = torch.tensor([[1., -1.], [1., -1.]])
t2 = torch.zeros_like(t1)
print(t2)

tensor([[0., 0.],
        [0., 0.]])


## torch.ones/torch.ones_like/torch.full/torch.full_like


In [6]:
print(torch.full((2, 3), 3.141592))

tensor([[3.1416, 3.1416, 3.1416],
        [3.1416, 3.1416, 3.1416]])


## torch.arange


In [7]:
# 创建等差的1维张量，长度为 (end-start)/step，需要注意数值区间为[start, end)。
# 主要参数：
# start (Number) – 数列起始值，默认值为0。the starting value for the set of points. Default: 0.
# end (Number) – 数列的结束值。
# step (Number) – 数列的等差值，默认值为1。
# out (Tensor, optional) – 输出的tensor，即该函数返回的tensor可以通过out进行赋值。
print(torch.arange(1, 2.51, 0.5))

tensor([1.0000, 1.5000, 2.0000, 2.5000])


## torch.linspace


In [8]:
# 创建均分的1维张量，长度为steps，区间为[start, end]。
# 主要参数：
# start (float) – 数列起始值
# end (float) – 数列结束值。
# steps (int) – 数列长度。
print(torch.linspace(3, 10, steps=5))
print(torch.linspace(1, 5, steps=3))

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])
tensor([1., 3., 5.])


## torch.logspace


In [17]:
# 创建对数均分的1维张量，长度为steps, 底为base。
# 主要参数：
# start (float) – 确定数列起始值为base^start
# end (float) – 确定数列结束值为base^end
# steps (int) – 数列长度。
# base (float) - 对数函数的底，默认值为10，此参数是在pytorch 1.0.1版本之后加入的。
print(np.log10(2.1135))
print(np.log10(3.5481))
print(np.log10(5.9566))
print(torch.logspace(start=0.1, end=1.0, steps=5))
print(torch.logspace(start=2, end=2, steps=1, base=2))

0.3250022521650377
0.5499958515306512
0.7749984371602154
tensor([ 1.2589,  2.1135,  3.5481,  5.9566, 10.0000])
tensor([4.])


## torch.eye


In [19]:
# 创建单位对角矩阵。
# 主要参数：
# n (int) - 矩阵的行数
# m (int, optional) - 矩阵的列数，默认值为n，即默认创建一个方阵
print(np.eye(3))
print(np.eye(3, 4))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


## torch.empty


In [51]:
# ：依size创建“空”张量，这里的“空”指的是不会进行初始化赋值操作。
# 主要参数：
# size (int...) - 张量维度
# pin_memory (bool, optional) - pinned memory 又称page locked memory，即锁页内存，该参数用来指示是否将tensor存
# 于锁页内存，通常为False，若内存足够大，建议设置为True，这样在转到GPU时会快一些。
torch.empty(2, 3)

tensor([[7.3190e+16, 1.2892e-42, 3.1416e+00],
        [3.1416e+00, 3.1416e+00, 3.1416e+00]])

## torch.empty_like(


In [52]:
# torch.empty_like之于torch.empty等同于torch.zeros_like之于torch.zeros，因此不再赘述。
torch.empty_like(t1)

tensor([[7.2111e+16, 1.2892e-42],
        [5.0000e+00, 0.0000e+00]])

## torch.empty_strided


In [56]:
# 依size创建“空”张量，这里的“空”指的是不会进行初始化赋值操作。
# 主要参数：
# stride (tuple of python:ints) - 张量存储在内存中的步长，是设置在内存中的存储方式。
# size (int...) - 张量维度
# pin_memory (bool, optional) - 是否存于锁页内存

# 这里 stride=(4,1)，表示：
# 在第一维（行），每跨 1 步，需要跳 4 个元素。
# 在第二维（列），每跨 1 步，需要跳 1 个元素。
# 这等价于 torch.empty((3,4))，使用的是默认的 行优先（Row-major） 存储方式。
# 创建一个 (3, 4) 形状的张量，步幅 (4, 1)，即默认的连续内存布局
tensor = torch.empty_strided((3, 4), (4, 1))
print(tensor)

# 这里 stride=(1, 3)，表示：
# 在第一维（行），每跨 1 步，只跳 1 个元素（行数据变得不连续）。
# 在第二维（列），每跨 1 步，需要跳 3 个元素。
# 这会导致列变得不连续，因为通常 PyTorch 张量是行优先存储的，而这里的 stride 让数据以列优先的方式存储。
# # 创建一个 (3, 4) 形状的张量，步幅 (1, 3)
tensor = torch.empty_strided((3, 4), (1, 3))
print(tensor)

# 这里 stride=(1,2)，表示：
# 在 第一维（行），每前进 1 步，跳 1 个元素。
# 在 第二维（列），每前进 1 步，跳 2 个元素（表示列是主维度）。
# 这个张量的 内存布局与其转置匹配，可以更高效地执行 tensor.t()。
# 创建一个 (2, 3) 形状的张量，并让它的步幅与转置 (3, 2) 形状匹配
tensor = torch.empty_strided((2, 3), (1, 2))  # 行步幅=1，列步幅=2
print(tensor)

tensor([[ 7.3759e+16,  1.2892e-42,  0.0000e+00,  1.1250e-05],
        [ 1.0842e-19,  2.1935e+00, -1.0842e-19,  2.3723e+00],
        [ 0.0000e+00,  2.5625e+00,  0.0000e+00,  0.0000e+00]])
tensor([[ 0.0000e+00,  1.1250e-05, -1.0842e-19,  2.5625e+00],
        [ 2.4026e+02,  1.0842e-19,  2.3723e+00,  0.0000e+00],
        [ 0.0000e+00,  2.1935e+00,  0.0000e+00,  0.0000e+00]])
tensor([[ 1.1250e-05,  2.5625e+00,  1.0842e-19],
        [-1.0842e-19,  2.4026e+02,  2.3723e+00]])


## torch.normal


In [ ]:
# 为每一个元素以给定的mean和std用高斯分布生成随机数
# 主要参数：
# mean (Tensor or Float) - 高斯分布的均值，
# std (Tensor or Float) - 高斯分布的标准差
# 特别注意事项：
# mean和std的取值分别有2种，共4种组合，不同组合产生的效果也不同，需要注意
# mean为张量，std为张量，torch.normal(mean, std, out=None)，每个元素从不同的高斯分布采样，分布的均值和标准差
# 由mean和std对应位置元素的值确定；
# mean为张量，std为标量，torch.normal(mean, std=1.0, out=None)，每个元素采用相同的标准差，不同的均值；
# mean为标量，std为张量，torch.normal(mean=0.0, std, out=None)， 每个元素采用相同均值，不同标准差；
# mean为标量，std为标量，torch.normal(mean, std, size, *, out=None) ，从一个高斯分布中生成大小为size的张量
mean = torch.arange(1, 11.)
std = torch.arange(1, 0, -0.1)
normal = torch.normal(mean=mean, std=std)
# normal第一个元素是从均值为1，标准差为1的高斯分布中采样得到的
# 第二个元素是从均值为2，标准差为0.9的高斯分布中采样得到的
print("mean: {}, \nstd: {}, \nnormal: {}".format(mean, std, normal))

mean: tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), 
std: tensor([1.0000, 0.9000, 0.8000, 0.7000, 0.6000, 0.5000, 0.4000, 0.3000, 0.2000,
        0.1000]), 
normal: tensor([ 1.1185,  2.0894,  3.5925,  4.4421,  4.8219,  5.0937,  7.3572,  8.4138,
         8.9422, 10.0821])
